language: python
python:
  - 2.7
  - 3.6
install:
  - pip install nose
  - ./setup.py develop
script:
  - nosetests tests
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master
